### ISSUE TITLE
add html file for google search engine 

### ISSUE THREAD

**Issue by fury-coder** [fury-coder/Coding-Library#12]

**Comment by falguni-k** [comment]
Hi, I would like to work on this issue. Please assign it to me.
Thanks!

**Comment by ujju20** [comment]
Please Assign me this issue.

**Comment by tamal-kundu** [comment]
ok @ujju20 i will assign u

**Comment by fury-coder** [comment]
ok @ujju20 i will assign please do it properly don't do spam

**Comment by ujju20** [comment]
> ok @ujju20 i will assign please do it properly don't do spam

Sure
