### ISSUE TITLE
Python automation scripts

### ISSUE THREAD

**Issue by Umesh-01** [fury-coder/Coding-Library#21]
## Description
I want to add these scripts in your repository...

- CoVID19 Info Scraping
- Quotes Scraping

**Comment by Umesh-01** [comment]
@fury-coder should I add these scripts??

**Comment by fury-coder** [comment]
yupp u can add the Covid 19 info but dont add the quotes it may break the rules..
for covid 19 script
add proper readme.md like about ,what it is, how u r going to do it and the .py code in a separate folder in python_scripts_
