### ISSUE TITLE
Add python folder with resources and hello world

### ISSUE THREAD

**Issue by fury-coder** [fury-coder/Coding-Library#3]
do add explnation (readme.md)
do add code snippets..
don't copy from other's repos..

**Comment by ashwinexe** [comment]
Can you assign me to this?

**Comment by nkhandelwal07** [comment]
Can you assign me this?

**Comment by dhananjay8968** [comment]
Resources as in how to learn python? and those resources to be added in a new README.MD file inside the python folder? . I am new to open source could you please help me with this.

**Comment by fury-coder** [comment]
yes @dhananjay8968 u got it..yes i will assign beginner contributors are always welcome

**Comment by dhananjay8968** [comment]
Kindly check the PR
