### ISSUE TITLE
Add c++ folder with resources and hello world

### ISSUE THREAD

**Issue by fury-coder** [fury-coder/Coding-Library#4]
do add explnation (readme.md)
do add code snippets..
don't copy from other's repos..

**Comment by tharani29** [comment]
Can you please assign this Issue to me [@tharani29 ]? Please provide need necessary permission for check-in.

**Comment by fury-coder** [comment]
yes i can assign u ..add the folllowing things 
create hello world folder and notes folder
under hello create readme.md that explains how c++ works how hello works
and in notes u can add C++ pdf notes
//happy hacking

**Comment by tharani29** [comment]
@fury-coder  Could you please provide me check-in permission?
I am getting below Permission error when i try to push my changes.
<img width="1042" alt="Screenshot 2021-10-05 at 1 14 37 PM" src="https://user-images.githubusercontent.com/703123/135981542-49dac55f-4069-4d1e-97c0-77abbbcee9bb.png">
?

**Comment by Ashwani132003** [comment]
@fury-coder  may I do this one?

**Comment by fury-coder** [comment]
@Ashwani32003 assigned

**Comment by fury-coder** [comment]
@tharani29 u can't directly push ur code without merging..only u can do is to raise a pr..kindly refer to the CONTRIBUTION.md

**Comment by pcpriyankapc** [comment]
Please assign me I can create a folder with wonderful resources and also explain hello world program

**Comment by tharani29** [comment]
> @tharani29 u can't directly push ur code without merging..only u can do is to raise a pr..kindly refer to the CONTRIBUTION.md fork the repo to ur account the push ur code to that then try raising a pr..then we will look into that.

I tried to push it to my branch so that I can create PR , but I was not able to do that because of permission .

**Comment by fury-coder** [comment]
@tharani29 may be u r facing some kind of internal issue ..but i can't do anything in that matter..
don't worry we will opening beginner friendly issues..
u can contribute to that.
